- name: Spark Cluster Deploy and Configuration
  hosts: spark
  tasks:

  - name: Installing dependencies to run a Spark Cluster
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - default-jdk
      - scala
    become: true

  - name: Extracting spark-2.4.3-bin-hadoop2.7.tgz into /opt/
    unarchive:
      src: http://mirrors.up.pt/pub/apache/spark/spark-2.4.3/spark-2.4.3-bin-hadoop2.7.tgz
      dest: /opt/
      remote_src: yes
    become: yes

  - name: Configuring the Spark workers (slaves)
    copy:
      dest: "/opt/spark-2.4.3-bin-hadoop2.7/conf/slaves"
      owner: sparkadmin
      group: sparkadmin
      mode: 0644
      content: |
        slave1
        slave2

  - name: Deploying the Spark unit file
    copy:
      src: spark.service
      dest: /etc/systemd/system
      owner: root
      group: root
      mode: 0755
    become: yes

  - name: Starting the Spark Cluster
    systemd:
      state: started
      enabled: yes
      daemon_reload: yes
      name: spark
    become: yes